import Chat from "@/components/ChatBot/Chat/Chat";
import Footer from "@/components/ChatBot/Footer/Footer";
import Header from "@/components/ChatBot/Header/Header";
import Head from "next/head";
import { ToastContainer } from "react-toastify";

export default function Home() {
  return (
    <>
      <Head>
        <title>Chatbot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <Chat />
        <Footer />
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </>
    </>
  );
}
